import type { Metadata } from "next";

//import "../globals.css";
import "../(frontend)/index.css";

import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/modules/header";
import Footer from "@/components/modules/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          <main id="app">
            <Header />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
